### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by corysimmons** [corysimmons/package-scripts#1]
- [ ] DRY up code
- [ ] Add conditionals for every possible scenario
- [ ] Try to use real JSON in as many places as possible instead of this string regex hackery
- [ ] Add watcher
- [ ] Add [Chalk](https://www.npmjs.com/package/chalk)
- [ ] Make sure path assignment is correct/intuitive/doesn't break any unix rules
- [ ] Try to make it so it doesn't iterate over every single `ps()` instance. Right now if you `console.log` anywhere in module.exports it will spam you. I'm sure I'm doing this wrong.
- [ ] Consider breaking functions out into their own file instead of housing them in same file as CLI
- [ ] Throw more descriptive and beautiful error messages for every scenario
